nodeLinker: node-modules

checksumBehavior: update
# compressionLevel: mixed

# # enableNetwork: true

# logFilters:
#   - code: YN0013
#     level: discard
#   - code: YN0019
#     level: discard

# npmRegistryServer: 'https://registry.npmjs.org'
