providers = []
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1727136237'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'
PORT = '8000'


[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']
nixLibs = ['gcc-unwrapped']
nixOverlays = [
  'https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz',
]
nixpkgsArchive = 'e05605ec414618eab4a7a6aea8b38f6fbbcc8f08'


[phases.install]
dependsOn = ['setup']
cmds = ['npm ci']
cacheDirectories = ['/root/.npm']
paths = ['/app/node_modules/.bin']


[phases.build]
dependsOn = ['install']
cmds = ['npm run build']
cacheDirectories = ['.next/cache', 'node_modules/.cache']


[start]
cmd = 'npm run start'
